name       : gpicview
homepage   : http://wiki.lxde.org/en/GPicView
version    : 0.2.5
release    : 5
source     :
    - http://netcologne.dl.sourceforge.net/project/lxde/GPicView%20%28image%20Viewer%29/0.2.x/gpicview-0.2.5.tar.xz : 38466058e53702450e5899193c4b264339959b563dd5cd81f6f690de32d82942
license    : GPL-2.0
component  : multimedia.graphics
summary    : A Simple and Fast Image Viewer for X
description: |
    GPicView is a simple and fast image viewer for X
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libturbojpeg)
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-gpicview-opens-in-center.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
