name        : gpicview
homepage    : http://lxde.sourceforge.net/gpicview/
version     : 0.2.4
release     : 3
source      :
    - http://liquidtelecom.dl.sourceforge.net/project/lxde/GPicView%20%28image%20Viewer%29/GpicView%200.2.4/gpicview-0.2.4.tar.gz : 99beb7df6765b386cd3f65b3ff77e9a25027a009db432f02bd60be8558f06ceb
homepage    : http://wiki.lxde.org/en/GPicView
license     : GPL-2.0+
component   : multimedia.graphics
summary     : A Simple and Fast Image Viewer for X
description : |
    GPicView is a simple and fast image viewer for X
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
